Repository ponylang/ponylang-website, pull requests merged in 2022-11, with the labels that each got.

#797 Last Week in Pony - November 6, 2022
  content/blog/last-week-in-pony-110622.md
Labels: DO NOT MERGE, discuss during sync

#802 Fix spelling and linting errors
  .spelling-wordlist.txt
  content/blog/last-week-in-pony-032817.md
  content/blog/last-week-in-pony-041117.md
  content/blog/last-week-in-pony-041717.md
Labels: discuss during sync

#801 Last Week in Pony - November 20, 2022
  .spelling-wordlist.txt
  content/blog/last-week-in-pony-112022.md
Labels: DO NOT MERGE

#803 Improvements to FAQ on causal ordering
  content/faq/index.md
Labels: discuss during sync

#805 Last Week in Pony - November 27, 2022
  content/blog/last-week-in-pony-112722.md
Labels: discuss during sync
